[T-6490][17.0][ADD] crm_lead_attach_related_saleorder_report
sygel-technology/sy-crm pull request #12
Opened 2024-08-09 11:02 UTC by Tisho99

2024-09-09 07:32 UTC, luis-ron approved these changes
Functional Review: LGTM 👍🏻 

Ask for a tecnical review if needed.

Ty

2024-09-09 09:37 UTC, manuelregidor requested changes

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/__manifest__.py
> +        "mail",
As sale_crm depends on sale, sale depends on sales_team and sales_team depends on mail, could't you remove the dependency on main in this module?

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/i18n/ca_ES.po
> +msgid "Send Quatations"
"Quotations" ( and "pressupost" in català).

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/i18n/es.po
> +msgid "Send Quatations"
Quotation

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/__init__.py
> +# Copyright 2020 Valentin Vinagre <valentin.vinagre@sygel.es>
Wrong copyright info

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/__manifest__.py
> +# Copyright 2020 Valentin Vinagre <valentin.vinagre@sygel.es>
Wrong copyright info

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/models/__init__.py
> +# Copyright 2020 Valentin Vinagre <valentin.vinagre@sygel.es>
Wrong copyright info

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/models/crm_lead.py
> +# Copyright 2020 Valentin Vinagre <valentin.vinagre@sygel.es>
Wrong copyright info

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/models/crm_lead.py
> +            compose_form_id = ir_model_data.get_object_reference(
Where is the get_object_reference method declared? I've checked the ir_model.py file in base module and it is not there. Am I missing something?

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/models/mail_compose_message.py
> +# Copyright 2020 Valentin Vinagre <valentin.vinagre@sygel.es>
Wrong copyright info

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/models/mail_compose_message.py
> +            lead_ids = [int(i) for i in sel.res_ids[1:-1].split(",")]
Have you tried to get the IDs through context? The _compute_res_ids method in mail.compose.message gets the IDs that way. Don't you think it would be cleaner in case that works?

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/models/mail_compose_message.py
> +        logging.error("Entramos al calculate_sale_attachments manin")
Remove logging

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/models/mail_compose_message.py
> +            logging.error(f"rendered_values: {rendered_values}")
Di you need to keep these loggings?

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/models/mail_compose_message.py
> +        lead_ids = [int(i) for i in self.res_ids[1:-1].split(",")]
Same as before. Maybe through context?

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/models/mail_compose_message.py
> +                logging.error(f"attachment_ids: {attachment_ids}")
Would you like to keep this logging?

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/models/mail_compose_message.py
> +            sale_ids.filtered(lambda x: x.state == "draft").write({"state": "sent"})
Have you considered using method "action_quotation_sent" in sale.order? If you use that method, all the operations related to marking the quotation as sent will be performed, not only a change in the state.

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/views/crm_lead.xml
> +<!-- Copyright 2020 Valentin Vinagre <valentin.vinagre@sygel.es>
Wrong copyright

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/views/mail_compose_message.xml
> +<!-- Copyright 2020 Valentin Vinagre <valentin.vinagre@sygel.es>
Wrong copyright

2024-09-09 09:37 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Could you generate the readme file through a readme folder?

2024-09-09 15:34 UTC, Tisho99 reviewed
Changes applied

2024-09-09 15:34 UTC, Tisho99 commented on crm_lead_attach_related_saleorder_report/models/crm_lead.py
> +# Copyright 2020 Valentin Vinagre <valentin.vinagre@sygel.es>
The task was about refactoring the module and changing its name, so the original file was not mine

2024-09-09 15:34 UTC, Tisho99 commented on crm_lead_attach_related_saleorder_report/models/mail_compose_message.py
> +            lead_ids = [int(i) for i in sel.res_ids[1:-1].split(",")]
I have tried it, however the context is empty inside my function

2024-09-09 15:34 UTC, Tisho99 commented on crm_lead_attach_related_saleorder_report/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Done

2024-09-09 16:40 UTC, Tisho99 commented
@manuelregidor 

I resolved all requested changes.

Do i need to add tests?

2024-09-10 06:29 UTC, manuelregidor commented on crm_lead_attach_related_saleorder_report/models/mail_compose_message.py
> +            lead_ids = [int(i) for i in sel.res_ids[1:-1].split(",")]
Could you try again please? I've just tried it and I think that the context does contain the information you need.

Context in _compute_check_add_sale_attachments method: {'lang': 'en_US', 'tz': 'Europe/Madrid', 'uid': 2, 'allowed_company_ids': [1], 'params': {'id': 25, 'cids': 1, 'menu_id': 194, 'action': 317, **'model': 'crm.lead'**, 'view_type': 'form'}, 'active_model': 'crm.lead', **'active_id': 25, 'active_ids': [25]**, 'default_model': 'crm.lead', 'default_res_ids': [25], 'default_composition_mode': 'comment', 'force_email': True}

Context in calculate_sale_attachments method: {'params': {'id': 25, 'cids': 1, 'menu_id': 194, 'action': 317, 'model': 'crm.lead', 'view_type': 'form'}, 'lang': 'en_US', 'tz': 'Europe/Madrid', 'uid': 2, 'allowed_company_ids': [1], **'active_model': 'crm.lead', 'active_id': 25, 'active_ids': [25]**, 'default_model': 'crm.lead', 'default_res_ids': [25], 'default_composition_mode': 'comment', 'force_email': True}

2024-09-10 06:30 UTC, manuelregidor commented
@Tisho99 As far as I know, all the modules in Sygel repositories must have tests from now on, so please, add them (unless @ValentinVinagre says the opposite).

2024-09-10 10:50 UTC, Tisho99 commented on crm_lead_attach_related_saleorder_report/models/mail_compose_message.py
> +            lead_ids = [int(i) for i in sel.res_ids[1:-1].split(",")]
Okay, done

2024-09-10 11:34 UTC, ValentinVinagre commented
@Tisho99 do test's please 💘 . correct @manuelregidor 😄

2024-09-10 11:51 UTC, manuelregidor approved these changes
LGTM However, as some importantes core changes have been applied, should you ask for a second functional review?

2024-09-13 11:12 UTC, ValentinVinagre commented
> LGTM However, as some importantes core changes have been applied, should you ask for a second functional review?

I think that to be on the safe side it wouldn't be a bad idea to review it again.

2024-09-13 11:12 UTC, ValentinVinagre commented
@luis-ron u could review again please?

2024-09-16 09:08 UTC, luis-ron approved these changes
Functional review: LGTM 👍🏻

2024-09-25 07:27 UTC, ValentinVinagre approved these changes
LGTM 👍🏻

2024-09-25 07:27 UTC, merged